#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ScrumHelper.Droid.Resource", IsApplication=true)]

namespace ScrumHelper.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int AcceptButton = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int CancelButton = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int DescriptionProjectEditText = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int EditProjectTabLayout = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int MainCaptionTextView = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int MainYourProjectsTextView = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int NameProjectEditText = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int StartMeetingButton = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int ViewListIterationProjectButton = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int ViewListMeetingButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ViewListPersonsProjectButton = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int ViewListProjectsButton = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int actionRow = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int captionRow = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int commandRow = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int editProjectButton = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int listProjectsListView = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int listRow = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int mainTabLay = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int tableRow1 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int tableRow2 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow3 = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int textView10 = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionProject = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditProject = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
